### ISSUE TITLE
Feature: toBeAccessible()

### ISSUE THREAD

**Issue by pke** [aryella-lacerda/react-native-accessibility-engine#104]
Would it be possible to create a Jest matcher so checks could read:

`expect(() => AccessibilityEngine.check(<Comp/>)).toBeAccessible()`

**Comment by pke** [comment]
Looks like this was easier than thought:

```ts
/* eslint-disable i18next/no-literal-string */
import { ReactElement } from "react"
import AccessibilityEngine from "react-native-accessibility-engine"

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Checks whether a component conforms to Accessibility A11y best practices.
       */
      toBeAccessible(): R
    }
  }
}

expect.extend({
  toBeAccessible(received: ReactElement) {
    try {
      AccessibilityEngine.check(received)
    } catch (error: any) {
      return {
        pass: false,
        message() {
          return error.message
        },
      }
    }
    return {
      pass: true,
      message() {
        return "Component is accessible.\nDoes it make sense to test a component for NOT being accessible?"
      },
    }
  },
})
```

This could be added as `expect-extend.js` to the root and configured in jest via 

```json
"jest": {
  "setupFilesAfterEnv": ["react-native-accessibility-engine/extend-expect.js"],
```
}

**Comment by aryella-lacerda** [comment]
👏👏👏👏👏

This looks awesome! I tested this out locally and it seems to be working well. A couple of things to note:

- A test using our custom jest matcher would actually look a little different from your first comment:
`expect(<Button />).toBeAccessible()`. I like how direct this is.
- Does it make sense to test a lack of accessibility? Probably not, but jest does provide the `.not` modifier by default, so we'd probably have to consider and test this anyway.

<img width="1309" alt="Screen Shot 2021-10-05 at 9 22 06 AM" src="https://user-images.githubusercontent.com/28730324/136021405-f423ceae-f928-4f2c-b4f9-4d925db82f72.png">

- See how the error message is formatted all in gray text? I took a look at [this comment](https://stackoverflow.com/a/64471550) on stackoverflow that explains how to use matcher utils to format error messages. Then I took a look at the [actual documentation of jest.expect](https://jestjs.io/docs/expect#expectextendmatchers) and it turns out that these matcher utils are actually available through `this.[util]` within the matchers.

Would you like to open a PR? This seems totally doable. 👍🏼

**Comment by pke** [comment]
thanks for considering a PR!
I am using this matcher in our test suites already quite successful! 
As for the `.not` matcher I already considered that ;) It would print out:

```
Component is accessible.
Does it make sense to test a component for NOT being accessible?
```

Not much we can do here, since jest matchers always have to provide the `.not` case.

**Comment by pke** [comment]
The problem with then '.not' stays the same if we would change the name, wouldn't it?
For other `A11y` matchers, do you think like contrast ratio or so? Where one could more fine grain the amount of accessibility features to test. Where `A11Compliant` would check for aria tags and contrast ratio one developer could decide to check for contrast ratio later in the development cycle?

**Comment by aryella-lacerda** [comment]
Philosophically speaking 👀 if you're going to test for a lack of accessibility, it might be better to just not test anything at all. 

Jest offers a [this.isNot](https://jestjs.io/docs/expect#thisisnot) helper which we could theoretically use to make a matcher that always fails if you use `.not`. But that might be excessive. At the very least, it would make for a highly opinionated matcher. 

As @pke suggested, a success message along the lines of `Does it make sense to test that a component is NOT accessible?` could be sufficient warning. Then the final decision on whether or not to use it would fall to the dev.

Thoughts?

**Comment by aryella-lacerda** [comment]
@jsamr I get what you mean about interpreting `.not.toBeAccessible` as _not visible to the screen reader_.  The same sort of confusion might also happen with the `accessible` prop: someone might interpret `.toBeAccessible()` as _contains an accessible={true} prop_. 

But in these cases, I don't believe the problem lies in a confusing matcher API. 🤔 These people would probably be confused about what accessibility actually is.

I believe that React Native's `accessible` prop, for example, IS confusing because it's using a word with an expansive definition to group elements on screen, which is a super specific thing.

I like `.toBeAccessible()` for a matcher that would run an element/instance against ALL the engine's rules. That's the closest we can get to testing accessibility as a whole. 

But we could also offer both matchers (toBeAccessible and toBeA11yCompliant), and make one an alias of the other, like a few of jest's built-in matchers.

Also I like the idea of the A11y prefix for more fine-grained matchers, similar to @testing-library/react-native's a11y queries. 👍🏼 

Thoughts?

**Comment by jsamr** [comment]
@aryella-lacerda The naming is a pretty opinionated thing ^^ If one day we want a matcher to test if an element is invisible to screen readers on both platforms, by checking recursively if at least one parent has `importantForAccessibility` or `accessibilityElementsHidden`, then I am not sure which name we could give. `toBeA11yHidden`?

Another point, one might think `toBeAccessible()` means *to have the accessible prop set to `true`*... I find the name a bit too generic to the point it encompasses very different notions and definitions.

**Comment by pke** [comment]
@aryella-lacerda @jsamr PR #126 created. Please comment.

**Comment by pke** [comment]
> Another point, one might think `toBeAccessible()` means _to have the accessible prop set to `true`_...

Well true, but for that there is the default jest matcher `.hasProperty`. And since `.toBeAccessible` needs to be made available via extension you can not accidentally confuse the two. Also there is the README and the code completion (hover help) in VSCode.
