### ISSUE TITLE
Awesome project 👍 

### ISSUE THREAD

**Issue by oblador** [aryella-lacerda/react-native-accessibility-engine#3]
I've been thinking of doing something similar to this and I just want to thank you for making it. It's really cool and I look forward to seeing it develop further. Thanks!

**Comment by aryella-lacerda** [comment]
Thank you! 😁 This project happened because it was something that I looked for but couldn't find. I'm especially happy that it can develop [while RN ramps up accessibility support](https://reactnative.dev/blog/2021/03/08/GAAD-React-Native-Accessibility). It'll prob be slow-going but totally worth it. ✌🏼
